# Generated by Django 5.0.1 on 2024-01-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('imageupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.imageupload')),
                ('graph_salary_level', models.ImageField(upload_to='', verbose_name='График уровень зарплат по годам')),
                ('graph_num_vacancy', models.ImageField(upload_to='', verbose_name='График количество вакансий по годам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
            bases=('main.imageupload', models.Model),
        ),
    ]
