# Generated by Django 5.0.1 on 2024-01-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
