# Generated by Django 5.0.1 on 2024-01-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='static/main/img/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
