# Generated by Django 5.0.1 on 2024-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='media/image/', verbose_name='Изображение'),
        ),
    ]
