# Generated by Django 5.0.1 on 2024-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_skills_graph_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_salary_level_by_city', models.ImageField(upload_to='image/', verbose_name='График уровень зарплат по городам')),
                ('graph_vacancy_fraction_by_city', models.ImageField(upload_to='image/', verbose_name='График доля вакансий по городам')),
                ('table', models.TextField(verbose_name='Таблица')),
            ],
        ),
    ]
