# Generated by Django 5.0.1 on 2024-01-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_imageupload_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Описание профессии')),
            ],
        ),
    ]
